spring:
  application:
    name: config-client
  cloud:
    discovery:
      enabled: true
      service-id: config-server
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8880
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/


