spring:
  application:
    name: bus-config-client
  cloud:
    discovery:
      enabled: true
      service-id: config-server
#    bus:
#      enabled: true
#      trace:
#        enabled: true
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
#  rabbitmq:
#    host: localhost
#    port: 15672
#    username: qiao
#    password: 123456

server:
  port: 8880
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/


